const fs = require('fs');
const path = require('path');
const matter = require('gray-matter');

const { marked } = require('marked');

const POSTS_DIR = path.join(process.cwd(), 'content/blog');
const CACHE_FILE = path.join(process.cwd(), 'src/lib/blog-cache.json');

function buildCache() {
  const files = fs.existsSync(POSTS_DIR)
    ? fs.readdirSync(POSTS_DIR).filter((f) => f.endsWith('.mdx') || f.endsWith('.md'))
    : [];

  const posts = files
    .map((file) => {
      const raw = fs.readFileSync(path.join(POSTS_DIR, file), 'utf-8');
      const { data, content } = matter(raw);
      
      // 1. Parse markdown to HTML
      let html = marked.parse(content);
      
      // 2. Replace <YouTube id="..." />
      html = html.replace(/<YouTube\s+id="([^"]+)"\s*\/>/g, (match, id) => {
        return `<div class="my-8 aspect-video w-full rounded-xl overflow-hidden shadow-lg border border-border"><iframe class="w-full h-full" src="https://www.youtube.com/embed/${id}" title="YouTube video player" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>`;
      });

      // 3. Replace <Callout title="..." type="...">...</Callout>
      html = html.replace(/<Callout\s+title="([^"]+)"(?:\s+type="([^"]+)")?>([\s\S]*?)<\/Callout>/g, (match, title, type, body) => {
        const isWarning = type === 'warning';
        const colorClass = isWarning ? 'bg-amber-500/10 border-amber-500' : 'bg-primary/10 border-primary';
        return `<div class="my-6 px-6 py-4 rounded-xl border-l-4 ${colorClass}"><h4 class="font-bold mb-2 mt-0">${title}</h4><div class="[&>p]:m-0 text-sm">${body}</div></div>`;
      });
      
      // 4. Strip stray wrapping <p> tags around block divs generated by marked
      html = html.replace(/<p>(<div[\s\S]*?<\/div>)<\/p>/g, '$1');

      // 5. Replace <FAQ> wrapper
      html = html.replace(/<FAQ>([\s\S]*?)<\/FAQ>/g, (match, body) => {
        return `<div class="my-8 border border-border rounded-xl p-6 bg-card"><h3 class="text-2xl font-bold mt-0 mb-4">Frequently Asked Questions</h3><div class="w-full">${body}</div></div>`;
      });

      // 6. Replace <FAQItem> elements
      html = html.replace(/<FAQItem\s+question="([^"]+)"(?:[^>]*)>([\s\S]*?)<\/FAQItem>/g, (match, question, body) => {
        return `<details class="border-b border-border group last:border-0"><summary class="flex flex-1 items-center justify-between py-4 font-semibold text-base hover:text-primary cursor-pointer list-none [&::-webkit-details-marker]:hidden">${question}<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="h-4 w-4 shrink-0 transition-transform duration-200 text-muted-foreground group-open:rotate-180"><path d="m6 9 6 6 6-6"/></svg></summary><div class="pb-4 pt-0 text-muted-foreground leading-relaxed prose prose-sm dark:prose-invert max-w-none">${body}</div></details>`;
      });

      return {
        frontmatter: data,
        content: html,
        rawContent: content,
        slug: data.slug || file.replace(/\.mdx?$/, ''),
      };
    })
    .filter((post) => !post.frontmatter.draft)
    .sort((a, b) => {
      const dateA = a.frontmatter.publishedAt ? new Date(a.frontmatter.publishedAt).getTime() : 0;
      const dateB = b.frontmatter.publishedAt ? new Date(b.frontmatter.publishedAt).getTime() : 0;
      return (Number.isNaN(dateB) ? 0 : dateB) - (Number.isNaN(dateA) ? 0 : dateA);
    });

  fs.writeFileSync(CACHE_FILE, JSON.stringify(posts, null, 2));
  console.log(`[Blog Cache] Generated successfully with ${posts.length} posts.`);
}

buildCache();
