const fs = require('fs');
const path = require('path');
const matter = require('gray-matter');

const { marked } = require('marked');

const POSTS_DIR = path.join(process.cwd(), 'content/blog');
const CACHE_FILE = path.join(process.cwd(), 'src/lib/blog-cache.json');

function buildCache() {
  const files = fs.existsSync(POSTS_DIR)
    ? fs.readdirSync(POSTS_DIR).filter((f) => f.endsWith('.mdx') || f.endsWith('.md'))
    : [];

  const posts = files
    .map((file) => {
      const raw = fs.readFileSync(path.join(POSTS_DIR, file), 'utf-8');
      const { data, content } = matter(raw);
      
      // 1. Parse markdown to HTML
      let html = marked.parse(content);
      
      // 2. Replace <YouTube id="..." />
      html = html.replace(/<YouTube\s+id="([^"]+)"\s*\/>/g, (match, id) => {
        return `<div class="my-8 aspect-video w-full rounded-xl overflow-hidden shadow-lg border border-border"><iframe class="w-full h-full" src="https://www.youtube.com/embed/${id}" title="YouTube video player" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>`;
      });

      // 3. Replace <Callout title="..." type="...">...</Callout>
      html = html.replace(/<Callout\s+title="([^"]+)"(?:\s+type="([^"]+)")?>([\s\S]*?)<\/Callout>/g, (match, title, type, body) => {
        const isWarning = type === 'warning';
        const colorClass = isWarning ? 'bg-amber-500/10 border-amber-500' : 'bg-primary/10 border-primary';
        return `<div class="my-6 px-6 py-4 rounded-xl border-l-4 ${colorClass}"><h4 class="font-bold mb-2 mt-0">${title}</h4><div class="[&>p]:m-0 text-sm">${body}</div></div>`;
      });
      
      // 4. Strip stray wrapping <p> tags around block divs generated by marked
      html = html.replace(/<p>(<div[\s\S]*?<\/div>)<\/p>/g, '$1');

      return {
        frontmatter: data,
        content: html,
        slug: data.slug || file.replace(/\.mdx?$/, ''),
      };
    })
    .filter((post) => !post.frontmatter.draft)
    .sort((a, b) => {
      const dateA = a.frontmatter.publishedAt ? new Date(a.frontmatter.publishedAt).getTime() : 0;
      const dateB = b.frontmatter.publishedAt ? new Date(b.frontmatter.publishedAt).getTime() : 0;
      return (Number.isNaN(dateB) ? 0 : dateB) - (Number.isNaN(dateA) ? 0 : dateA);
    });

  fs.writeFileSync(CACHE_FILE, JSON.stringify(posts, null, 2));
  console.log(`[Blog Cache] Generated successfully with ${posts.length} posts.`);
}

buildCache();
